### PR TITLE
Update JOSM core icons

### PR DESCRIPTION
**Pull request by don-vip**

### CODE REVIEW

**Comment by yohanboniface** [comment]
Which JOSM version is impacted, the current one or should we wait a bit before merging?

**Comment by don-vip** [comment]
I have merged a lot of change of icons that occured in the past two years, there's no need to wait further. In fact I have created a new unit test to detect invalid presets, and this one is a bad boy, see https://josm.openstreetmap.de/jenkins/job/JOSM/lastCompletedBuild/jdk=JDK7/testReport/org.openstreetmap.josm.gui.preferences.map/TaggingPresetPreferenceTest/testValidityOfAvailablePresets/ for details.

It is not yet finished however: you reference a lot of private icons you don't provide with the presets. You need to release the presets as a zip archive containing all of these icons, like the TrafficSigns presets, or Kendzi3DBuildings for example.

The list of icons I didn't find is:

ERROR: Failed to locate image 'icons/group_home.png'
ERROR: Failed to locate image 'icons/ambulantorycare.png'
ERROR: Failed to locate image 'icons/social_living.png'
ERROR: Failed to locate image 'icons/sheltered_workshop.png'
ERROR: Failed to locate image 'icons/foodbank.png'
ERROR: Failed to locate image 'icons/outpatient_care.png'
ERROR: Failed to locate image 'icons/social_shelter.png'
ERROR: Failed to locate image 'icons/outreach.png'
ERROR: Failed to locate image 'icons/group_home.png'

ERROR: Failed to locate image 'presets/JusticeScales.png'

ERROR: Failed to locate image 'icons/trade.png'
ERROR: Failed to locate image 'icons/glaziery.png'
ERROR: Failed to locate image 'icons/shoe_repair.png'
ERROR: Failed to locate image 'icons/blacksmith.png'
ERROR: Failed to locate image 'icons/shoemaker.png'
ERROR: Failed to locate image 'icons/buero.png'
ERROR: Failed to locate image 'icons/employment_agency.png'
ERROR: Failed to locate image 'icons/architect.png'
ERROR: Failed to locate image 'icons/government.png'
ERROR: Failed to locate image 'icons/employment_agency.png'
ERROR: Failed to locate image 'icons/government.png'
ERROR: Failed to locate image 'icons/research.png'
ERROR: Failed to locate image 'icons/estate_agent.png'
ERROR: Failed to locate image 'icons/it.png'
ERROR: Failed to locate image 'icons/ngo.png'
ERROR: Failed to locate image 'icons/quango.png'
ERROR: Failed to locate image 'icons/company.png'
ERROR: Failed to locate image 'icons/lawyer.png'
ERROR: Failed to locate image 'icons/travel_agent.png'
ERROR: Failed to locate image 'icons/accountant.png'
ERROR: Failed to locate image 'icons/telecommunication.png'
ERROR: Failed to locate image 'icons/insurance.png'
ERROR: Failed to locate image 'icons/newspaper.png'
ERROR: Failed to locate image 'icons/ambulance_station.png'

**Comment by don-vip** [comment]
We plan to release new JOSM very soon, can this PR please be merged? It helps us to maintain all extensions out there. Thanks.

**Comment by yohanboniface** [comment]
Sorry, I wanted to take a bit of time to understand a bit more, but I've missed this time :(

**Comment by don-vip** [comment]
I can explain more, no problem. We regularly update core icons by moving them, renaming them, or converting them from PNG to SVG. These changes must be reflected to external presets and map styles. Until now we did not have an automatic way to detect impacted extensions, but I have a created a new unit test that performs this task.

The goal is to have the test OK (not a single extension that references invalid icon).

In hotosm' case, there are still private icons that are not shipped with the presets. 

To resolve this, 3 choices:
1. a zip archive containing the XML and the icons must be provided, instead of the plain XML file
2. use proper (http) links to these images
3. use only core JOSM icons

Other possibility is to submit JOSM patches to include these icons in new internal presets.

**Comment by yohanboniface** [comment]
> 1. a zip archive containing the XML and the icons must be provided, instead of the plain XML file

Yeah, I remember releasing the preset with a ZIP, some years ago. I think we just linked to the github release zip, is it possible?

**Comment by don-vip** [comment]
It might work. Do you have such a link? I can test it right now.

**Comment by yohanboniface** [comment]
Humm, I'm mixing with JOSM style: https://josm.openstreetmap.de/ticket/8686 sorry. There is no release here. :/

**Comment by don-vip** [comment]
that's exactly the same problem, yes :) So in theory, releasing a version and linking to the zip file on JOSM wiki should fix the issues.

**Comment by don-vip** [comment]
Can you please make a release, then?

**Pull request merged**
